- Assets/InputSystem.meta
- Assets/InputSystem/JHInputSystem.meta
- Assets/InputSystem/JHInputSystem/JHCharacterAction.inputactions
- Assets/InputSystem/JHInputSystem/JHCharacterAction.inputactions.meta
- Assets/Material.meta
- Assets/Material/JHMaterial.meta
- Assets/Material/JHMaterial/JHDark.mat
- Assets/Material/JHMaterial/JHDark.mat.meta
- Assets/Scenes/JHTest.unity
- Assets/Scenes/JHTest.unity.meta
- Assets/Scripts/JHTest.meta
- Assets/Scripts/JHTest/JHMoveTest.cs
- Assets/Scripts/JHTest/JHMoveTest.cs.meta
> [Feat] : 아이소메트릭 카메라 생성

- Assets/Scenes/JHTest.unity
- Assets/Scripts/JHTest/JHDash.cs
- Assets/Scripts/JHTest/JHDash.cs.meta
- Assets/Scripts/JHTest/JHMoveTest.cs
- Assets/Scripts/JHTest/JHMoveTest01.cs
- Assets/Scripts/JHTest/JHMoveTest01.cs.meta
> [Feat] : 대쉬 가속 감속

- Assets/Scenes/JHTest.unity
- Assets/Scripts/Character/CharacterDash.cs
- Assets/Scripts/Character/CharacterDash.cs.meta
- Assets/Scripts/Managers/CharacterManager.cs
> [Feat] : 게임매니저에 bool값 추가

- Assets/Scenes/MSTest.unity
- Assets/Scripts/Character/CharacterMovement.cs
점프에서 약점프 이후 강점프 시, 점프가 높게되는 버그 발견
> [Fix] : 점프 버그 발견 수정요청

- Assets/Materials/Wine.mat
- Assets/Materials/Wine.mat.meta
- Assets/Prefabs/Managers.meta
- Assets/Prefabs/Managers/CharacterManager.prefab
- Assets/Prefabs/Managers/CharacterManager.prefab.meta
- Assets/Prefabs/Managers/Input Manager.prefab
- Assets/Prefabs/Managers/Input Manager.prefab.meta
- Assets/Prefabs/Player.meta
- Assets/Prefabs/Player/Player.prefab
- Assets/Prefabs/Player/Player.prefab.meta
- Assets/Scenes/MSTest.unity
- Assets/Scenes/SHTest.unity
- Assets/Scripts/Character/CharacterJump.cs
점프 시에 중력에 추가적으로 m_gravityMultiflier를 곱해주는데,
이 값이 일시적으로 적용되어야하는데 대입연산자로 들어가면서 이후 이 값을 사용하는 문에서 오류가 발생하였습니다.
확인하였고 현재 해결되었습니다.
> [Fixed] : 빠르게 더블점프 시 점프가 너무 강하게 발생하던 문제 수정

- Assets/Scenes/JHTest.unity
> [Fix] : 구도별 카메라

- Assets/Scenes/SH/JumpMap.unity
- Assets/Scenes/SH/JumpMap.unity.meta
- Assets/Scenes/SH/SHTest_CameraZone.unity
[Fixed] : SHTest_CameraZone과 FollowingCamera의 이름이 반대로 되어있던 문제 수정
> [Fixed] : SHTest_CameraZone과 FollowingCamera의 이름이 반대로 되어있던 문제 수정

- Assets/Prefabs/Cameras/BackViewVcam.prefab
- Assets/Prefabs/Cameras/BackViewVcam.prefab.meta
- Assets/Scenes/MSTest.unity
- Assets/Scripts/BossStageTrigger.cs
- Assets/Scripts/BossStageTrigger.cs.meta
- Assets/Scripts/Character/CharacterDash.cs
- Assets/Scripts/Character/CharacterMovement.cs
- Assets/Scripts/Managers/CharacterManager.cs
- Assets/Scripts/Managers/GameManager.cs
- Assets/Scripts/Managers/GameManager.cs.meta
> [Feat] : GameManager 트리거 완성

- Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_Wide.prefab
- Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_Wide.prefab.meta
- Assets/Scenes/JHTest.unity
- Assets/Scripts/Obstacles/FallingObstacle.cs
- Assets/Scripts/Obstacles/FallingObstacleSpawner.cs
> [Feat]: Obstacle Wide추가

- Assets/Scripts/Character/CharacterJump.cs
[Feat] : CharacterJump.isJumping을 CharacterManager.isJump로 이동
> [Feat] : CharacterJump.isJumping을 CharacterManager.isJump로 이동

- Assets/Scripts/Character/CharacterDash.cs
> [Fix] : 점프시 연속대쉬제거

- Assets/Prefabs/Obstacle/FallingObstacle_Circle.prefab
- Assets/Prefabs/Obstacle/FallingObstacle_Rectangle.prefab
- Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_10x10.prefab
- Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_10x10.prefab.meta
- Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_15x15.prefab
- Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_15x15.prefab.meta
- Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_6x6.prefab
- Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_6x6.prefab.meta
- Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_Big.prefab
- Assets/Scenes/JHTest.unity
- Assets/Scripts/Camera/CameraRayAplha.cs
- Assets/Scripts/Camera/CameraRayAplha.cs.meta
- Assets/Scripts/Obstacles/FallingObstacleSpawner.cs
> [Feat] : 카메라 앞 오브젝트 반투명화, 대쉬 레벨디자인

- Assets/DisableOnAwake.cs
- Assets/DisableOnAwake.cs.meta
- Assets/InputSystem.inputsettings.asset
- Assets/Prefabs/Cameras/LookAtPosition.prefab
- Assets/Prefabs/Cameras/LookAtPosition.prefab.meta
- Assets/Prefabs/Cameras/ZoneVcams.meta
- Assets/Prefabs/Cameras/ZoneVcams/FixedVcam.prefab
- Assets/Prefabs/Cameras/ZoneVcams/FixedVcam.prefab.meta
- Assets/Prefabs/Cameras/ZoneVcams/PlayerFollowingVcam.prefab
- Assets/Prefabs/Cameras/ZoneVcams/PlayerFollowingVcam.prefab.meta
- Assets/Scenes/SH/SHTest_Isometry.unity
- Assets/Scenes/SH/SHTest_Isometry.unity.meta
- Assets/Scripts/Camera/CameraZone.cs
- Assets/Scripts/Camera/PlayerFollowingCamera.cs
- Assets/Scripts/Character/CharacterMovement.cs
- Assets/Scripts/Managers/CharacterManager.cs
카메라가 고정되었을 때, 특정 방향을 기준으로 이동할 수 있게 하는 로직 제작
> [Feat] : Fixed Camera Move 제작

- Assets/Materials/GridBase_Ground.mat
- Assets/Materials/GridBase_Ground.mat.meta
- Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_30x30_1.prefab
- Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_30x30_1.prefab.meta
- Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_30x30_2.prefab
- Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_30x30_2.prefab.meta
- Assets/Scenes/JHTest.unity
- Assets/Scripts/Obstacles/FallingObstacleSpawner.cs
> [Faet] : Obstacle 더미 추가

- Assets/Scenes/MSTest.unity
- Assets/Scripts/Boss/Boss.cs
> [Feat] : 보스 1차 기믹 반복하는 코드 추가

- Assets/Prefabs/DashStage.prefab
- Assets/Prefabs/DashStage.prefab.meta
- Assets/Prefabs/Obstacle/FallingObstacle_Circle.prefab
- Assets/Prefabs/Obstacle/FallingObstacle_Rectangle.prefab
- Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_10x10.prefab
- Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_15x15.prefab
- Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_2x30.prefab
- Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_2x30.prefab.meta
- Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_40x30.prefab
- Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_5x30.prefab
- Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_60x30.prefab
- Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_6x6.prefab
- Assets/Prefabs/Obstacle/ObstacleSpawner.meta
- Assets/Prefabs/Obstacle/ObstacleSpawner/ObstacleSpawner_1.prefab
- Assets/Prefabs/Obstacle/ObstacleSpawner/ObstacleSpawner_1.prefab.meta
- Assets/Prefabs/Obstacle/ObstacleSpawner/ObstacleSpawner_2.prefab
- Assets/Prefabs/Obstacle/ObstacleSpawner/ObstacleSpawner_2.prefab.meta
- Assets/Prefabs/Obstacle/ObstacleSpawner/ObstacleSpawner_3.prefab
- Assets/Prefabs/Obstacle/ObstacleSpawner/ObstacleSpawner_3.prefab.meta
- Assets/Prefabs/Obstacle/ObstacleSpawner/ObstacleSpawner_4.prefab
- Assets/Prefabs/Obstacle/ObstacleSpawner/ObstacleSpawner_4.prefab.meta
- Assets/Prefabs/Obstacle/ObstacleSpawner/ObstacleSpawner_5.prefab
- Assets/Prefabs/Obstacle/ObstacleSpawner/ObstacleSpawner_5.prefab.meta
- Assets/Prefabs/Obstacle/ObstacleSpawner/ObstacleSpawner_6.prefab
- Assets/Prefabs/Obstacle/ObstacleSpawner/ObstacleSpawner_6.prefab.meta
- Assets/Prefabs/Obstacle/ObstacleSpawner/ObstacleSpawner_6_1.prefab
- Assets/Prefabs/Obstacle/ObstacleSpawner/ObstacleSpawner_6_1.prefab.meta
- Assets/Scripts/Obstacles/FallingObstacleSpawner.cs
- ProjectSettings/TagManager.asset
> [Feat] : DashStage 추가

- Assets/Materials/GridBase_Step.mat
- Assets/Materials/GridBase_Step.mat.meta
- Assets/Prefabs/DashStage.prefab
- Assets/Scenes/MainJH.unity
- Assets/Scripts/Camera/CameraRayAplha.cs
> [Feat] : DashStage 레벨, 카메라존 수정

- Assets/InputSystem.inputsettings.asset
- Assets/InputSystem/CharacterAction.inputactions
- Assets/Scenes/MainMS.unity
- Assets/Scripts/Character/CharacterJump.cs
- Assets/Scripts/Character/CharacterMovement.cs
[[Fix] : 캐릭터 움직임 없을 시 혼자 회전하는 오류 수정
> [Fix] : 캐릭터 움직임 없을 시 혼자 회전하는 오류 수정

- Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_15x15_B.prefab
- Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_15x15_B.prefab.meta
- Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_2x85_B.prefab
- Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_2x85_B.prefab.meta
- Assets/Prefabs/Obstacle/ObstacleSpawner/ObstacleSpawner_7.prefab
- Assets/Prefabs/Obstacle/ObstacleSpawner/ObstacleSpawner_7.prefab.meta
- Assets/Prefabs/Save_SpownPoint.prefab
- Assets/Prefabs/Save_SpownPoint.prefab.meta
- Assets/Prefabs/UI_WorldSpace.prefab
- Assets/Prefabs/UI_WorldSpace.prefab.meta
- Assets/Scenes/MainJH.unity
- Assets/Scripts/Obstacles/FallingObstacleBoss.cs
- Assets/Scripts/Obstacles/FallingObstacleBoss.cs.meta
> [Feat] : 보스패턴 추가

- Assets/Scenes/MainSH.unity
- Assets/Scripts/Character/CharacterDash.cs
- Assets/Scripts/Character/CharacterJump.cs
- Assets/Scripts/Character/CharacterMovement.cs
- Assets/Scripts/Gimics/BallGoal.cs
- Assets/Scripts/Managers/CameraManager.cs
- Assets/Scripts/Managers/CharacterManager.cs
- Assets/Scripts/Projectiles/ProjectileSpawner.cs
- Assets/Scripts/Utilities/PlayerTeleporter.cs
- 점프하지 않고 떨어질 경우 대쉬 여러번 하는 오류 수정
- CharacterJump의 isOnGround를 CharacterManager로 이동
> [Fix] : 점프하지 않고 떨어질 경우 대쉬 여러번 하는 오류 수정 외 1

- Assets/Scenes/MainSH.unity
- Assets/Scripts/Character/CharacterMovement.cs
- Assets/Scripts/Obstacles/SuperJumpStep.cs
> [Fix] : CharacterMovement의 OnMovement와 FixedMove 부분이 CanMove = false여도 동작하던 문제 해결

- Assets/Prefabs/Maps/Map_SH1.prefab
- Assets/Scenes/MainSH.unity
- Assets/Scripts/Utilities/PlayerTeleporter.cs
진행이 불가능하던 오류 수정, SpawnPoint 위치가 맞지 않던 오류 수정
> [Fix] : SpawnPoint 위치 조정

- Assets/Prefabs/BossStage.prefab
- Assets/Scenes/MSTest.unity
- Assets/Scripts/Boss/Boss.cs
- Assets/Scripts/Boss/BossCharge.cs
- Assets/Scripts/Boss/BossRedObstacle.cs
- Assets/Scripts/Managers/BossManager.cs
> [Fix] : BossManager 스크립트 수정

- Assets/Scenes/MSTest.unity
- Assets/Scripts/Boss/Boss.cs
- Assets/Scripts/Character/CharacterDash.cs
- Assets/Scripts/Character/CharacterJump.cs
이제 장애물을 맞으면 더욱더 아파하면서 빙글빙글 돌아버립니다.
> [Feat] : 플레이어 움직임 스턴 모션과 동기화 추가

- Assets/Materials/Colors/BagColor.mat
- Assets/Materials/Colors/BagColor.mat.meta
- Assets/Prefabs/Player/MainPlayer.prefab
> [Feat] : 플레이어 회사원 컨셉 추가

- Assets/Scenes/JHBossTest.unity
- Assets/Scripts/Obstacles/FallingObstacleBossManager.cs
- Assets/Scripts/Obstacles/FallingObstacleSpawner_RD.cs
> [Fix] : Obstacle랜덤생성 수정

- Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_100x100B.prefab
- Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_100x100B.prefab.meta
- Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_5x100_B.prefab
- Assets/Prefabs/Obstacle/FallingObstacle_Rectangle_5x100_B.prefab.meta
- Assets/Prefabs/Obstacle/ObstacleSpawner/FallingObstacleBossManager.prefab
- Assets/Scenes/JHBossTest.unity
- Assets/Scripts/Obstacles/FallingObstacle_B.cs
- Assets/Scripts/Obstacles/FallingObstacle_B.cs.meta
Obstacle 낙하 위험표시 범위 변경
Boss스테이지 낙하 피격판정 변경
> [Fix] : Obstacle 낙하 위험표시 범위

- Assets/Prefabs/DashStage.prefab
- Assets/Prefabs/Save_SpownPoint.prefab
ObstacleSpawner, savePoint 위치변경
> [Fix] : ObstacleSpawner, savePoint 위치변경

- Assets/Prefabs/Boss.prefab
- Assets/Prefabs/BossStage.prefab
- Assets/Prefabs/Cameras/BossPhase2Cam.prefab
- Assets/Prefabs/Player/MainPlayer.prefab
- Assets/Scenes/MSTest.unity
- Assets/Scenes/MainSH.unity
- Assets/Scenes/SH/MainSH_Temp.unity
- Assets/Scripts/Boss/Boss.cs
- Assets/Scripts/Boss/BossBlackObstacle.cs
- Assets/Scripts/Boss/BossPhase2.cs
- Assets/Scripts/Boss/BossRedObstacle.cs
- Assets/Scripts/Character/CharacterDash.cs
- Assets/Scripts/Character/CharacterMovement.cs
- Assets/Scripts/Managers/BossManager.cs
- Assets/Scripts/Managers/CharacterManager.cs
> [Fix] : 넥타이 선글라스에 충돌판정 수정

- Assets/Scripts/Obstacles/FallingObstacle_B.cs
> [Fix] : 보스 장애물 리스폰 위치 수정

- Assets/Scenes/MainSH.unity
- Assets/Scripts/Managers/BossManager.cs
- Assets/Scripts/Managers/CharacterManager.cs
> [Fix] : 보스 기믹 밸런스 조절 완료 엔딩 추가

- Assets/Scenes/MainSH.unity
- Assets/Scripts/Managers/BossManager.cs
- ProjectSettings/EditorBuildSettings.asset
> [Feat] : 시작,클리어씬 연결 

- Assets/Prefabs/BossStage 1.prefab
- Assets/Prefabs/DashStage.prefab
> [Fix] : 시작계단, 보스외벽 수정
